AP_MISSING_TOWNS_BY_DISTRICT = {
    "1. NTR District": [
        {"town": "Vatsavai", "pincode": "521178", "category": "Mandal HQ & Border Town"},
        {"town": "Penuganchiprolu", "pincode": "521185", "category": "Mandal HQ & Temple Town"},
        {"town": "Chandarlapadu", "pincode": "521182", "category": "Mandal HQ"},
        {"town": "Veerullapadu", "pincode": "521181", "category": "Mandal HQ"},
        {"town": "G.Konduru", "pincode": "521229", "category": "Mandal HQ"},
        {"town": "A.Konduru", "pincode": "521226", "category": "Mandal HQ"},
        {"town": "Gampalagudem", "pincode": "521236", "category": "Mandal HQ"},
        {"town": "Reddigudem", "pincode": "521215", "category": "Mandal HQ"},
        {"town": "Enikepadu (Vijayawada East)", "pincode": "521108", "category": "Major Commercial Suburb"},
        {"town": "Poranki (Vijayawada East)", "pincode": "521137", "category": "High-Density Commercial Corridor"},
        {"town": "Prasadampadu", "pincode": "521108", "category": "Commercial Suburb"},
    ],
    "2. Krishna District": [
        {"town": "Bantumilli", "pincode": "521324", "category": "Mandal HQ"},
        {"town": "Bapulapadu", "pincode": "521105", "category": "Mandal HQ & Highway Town"},
        {"town": "Ghantasala", "pincode": "521133", "category": "Mandal HQ & Heritage Town"},
        {"town": "Guduru (Krishna)", "pincode": "521149", "category": "Mandal HQ"},
        {"town": "Kankipadu", "pincode": "521151", "category": "Mandal HQ & Suburb Hub"},
        {"town": "Koduru (Krishna)", "pincode": "521128", "category": "Mandal HQ"},
        {"town": "Kruthivennu", "pincode": "521324", "category": "Mandal HQ"},
        {"town": "Movva", "pincode": "521135", "category": "Mandal HQ & Cultural Town"},
        {"town": "Mopidevi", "pincode": "521125", "category": "Mandal HQ & Temple Town"},
        {"town": "Mudinepalli", "pincode": "521321", "category": "Mandal HQ"},
        {"town": "Nagayalanka", "pincode": "521120", "category": "Mandal HQ & Port Zone"},
        {"town": "Nandivada", "pincode": "521327", "category": "Mandal HQ"},
        {"town": "Pedaparupudi", "pincode": "521321", "category": "Mandal HQ"},
        {"town": "Penamaluru", "pincode": "521139", "category": "Major Commercial Suburb"},
        {"town": "Thotlavalluru", "pincode": "521163", "category": "Mandal HQ"},
        {"town": "Unguturu (Krishna)", "pincode": "521260", "category": "Mandal HQ"},
    ],
    "3. Visakhapatnam District": [
        {"town": "Anandapuram", "pincode": "530052", "category": "Mandal HQ & Growth Corridor"},
        {"town": "Padmanabham", "pincode": "531219", "category": "Mandal HQ"},
        {"town": "Seethammadhara", "pincode": "530013", "category": "Major Urban Retail Hub"},
        {"town": "Gopalapatnam", "pincode": "530027", "category": "Major Commercial & Transit Hub"},
        {"town": "Maharanipeta", "pincode": "530002", "category": "Urban Commercial Zone"},
        {"town": "Mulagada", "pincode": "530011", "category": "Industrial & Port Suburb"},
    ],
    "4. Anakapalli District": [
        {"town": "Devarapalli (Anakapalli)", "pincode": "531033", "category": "Mandal HQ"},
        {"town": "K.Kotapadu", "pincode": "531032", "category": "Mandal HQ"},
        {"town": "Kasimkota", "pincode": "531031", "category": "Mandal HQ & Highway Town"},
        {"town": "Kotauratla", "pincode": "531085", "category": "Mandal HQ"},
        {"town": "Madugula", "pincode": "531027", "category": "Mandal HQ & Assembly Constituency"},
        {"town": "Munagapaka", "pincode": "531002", "category": "Mandal HQ"},
        {"town": "Nakkapalli", "pincode": "531081", "category": "Mandal HQ & Highway/Industrial Hub"},
        {"town": "Parawada", "pincode": "531021", "category": "Mandal HQ & Pharma SEZ Hub"},
        {"town": "Rambilli", "pincode": "531061", "category": "Mandal HQ & Naval SEZ Zone"},
        {"town": "Ravikamatham", "pincode": "531114", "category": "Mandal HQ"},
        {"town": "Rolugunta", "pincode": "531114", "category": "Mandal HQ"},
        {"town": "S.Rayavaram", "pincode": "531127", "category": "Mandal HQ"},
        {"town": "Cheedikada", "pincode": "531028", "category": "Mandal HQ"},
        {"town": "Butchayyapeta", "pincode": "531026", "category": "Mandal HQ"},
    ],
    "5. Alluri Sitharama Raju (ASR) District": [
        {"town": "Ananthagiri (ASR)", "pincode": "531149", "category": "Mandal HQ & Tourism Hub"},
        {"town": "G.Madugula", "pincode": "531029", "category": "Mandal HQ"},
        {"town": "GK Veedhi (Gudem Kotha Veedhi)", "pincode": "531133", "category": "Mandal HQ"},
        {"town": "Hukumpeta", "pincode": "531077", "category": "Mandal HQ"},
        {"town": "Koyyuru", "pincode": "531084", "category": "Mandal HQ"},
        {"town": "Munchingiputtu", "pincode": "531040", "category": "Mandal HQ"},
        {"town": "Pedabayalu", "pincode": "531040", "category": "Mandal HQ"},
        {"town": "Dumbriguda", "pincode": "531151", "category": "Mandal HQ"},
        {"town": "Addateegala", "pincode": "533285", "category": "Mandal HQ"},
        {"town": "Devipatnam", "pincode": "533286", "category": "Mandal HQ & Riverfront Hub"},
        {"town": "Gangavaram (ASR)", "pincode": "533285", "category": "Mandal HQ"},
        {"town": "Rajavommangi", "pincode": "533436", "category": "Mandal HQ"},
        {"town": "Y.Ramavaram", "pincode": "533283", "category": "Mandal HQ"},
        {"town": "Kunavaram", "pincode": "507121", "category": "Mandal HQ & River Junction"},
        {"town": "VR Puram (Vararamachandrapuram)", "pincode": "507126", "category": "Mandal HQ"},
        {"town": "Velairpadu", "pincode": "534442", "category": "Mandal HQ"},
        {"town": "Kukunoor", "pincode": "534442", "category": "Mandal HQ"},
    ],
    "6. Guntur District": [
        {"town": "Chebrolu (Guntur)", "pincode": "522212", "category": "Mandal HQ & Heritage/University Town"},
        {"town": "Duggirala", "pincode": "522330", "category": "Mandal HQ & Turmeric Trade Hub"},
        {"town": "Kakumanu", "pincode": "522703", "category": "Mandal HQ"},
        {"town": "Kollipara", "pincode": "522304", "category": "Mandal HQ"},
        {"town": "Mediconduru", "pincode": "522438", "category": "Mandal HQ"},
        {"town": "Pedanandipadu", "pincode": "522235", "category": "Mandal HQ & Agricultural Market"},
        {"town": "Phirangipuram", "pincode": "522529", "category": "Mandal HQ"},
        {"town": "Vatticherukuru", "pincode": "522212", "category": "Mandal HQ"},
    ],
    "7. Bapatla District": [
        {"town": "Amruthalur", "pincode": "522325", "category": "Mandal HQ"},
        {"town": "Ballikurava", "pincode": "523260", "category": "Mandal HQ & Granite Industry"},
        {"town": "Chinaganjam", "pincode": "523135", "category": "Mandal HQ & Salt/Fisheries Town"},
        {"town": "Janakavarampanguluru (Panguluru)", "pincode": "523261", "category": "Mandal HQ"},
        {"town": "Karlapalem", "pincode": "522111", "category": "Mandal HQ"},
        {"town": "Karamchedu", "pincode": "523168", "category": "Mandal HQ & High-Yield Market"},
        {"town": "Martur", "pincode": "523261", "category": "Mandal HQ & Major Granite Trade Hub"},
        {"town": "Nizampatnam", "pincode": "522314", "category": "Mandal HQ & Fishing Harbor"},
        {"town": "Nagaram (Bapatla)", "pincode": "522268", "category": "Mandal HQ"},
        {"town": "Tsunduru", "pincode": "522259", "category": "Mandal HQ"},
        {"town": "Santamaguluru", "pincode": "523302", "category": "Mandal HQ"},
    ],
    "8. Palnadu District": [
        {"town": "Atchampet (Palnadu)", "pincode": "522409", "category": "Mandal HQ"},
        {"town": "Bellamkonda", "pincode": "522411", "category": "Mandal HQ"},
        {"town": "Bollapalle", "pincode": "522657", "category": "Mandal HQ"},
        {"town": "Dachepalle", "pincode": "522414", "category": "Mandal HQ & Limestone Industry Hub"},
        {"town": "Durgi", "pincode": "522612", "category": "Mandal HQ & Stone Crafting Town"},
        {"town": "Ipuru", "pincode": "522658", "category": "Mandal HQ"},
        {"town": "Krosuru", "pincode": "522410", "category": "Mandal HQ"},
        {"town": "Muppalla", "pincode": "522408", "category": "Mandal HQ"},
        {"town": "Nakarikallu", "pincode": "522615", "category": "Mandal HQ & Quarry Belt"},
        {"town": "Nuzendla", "pincode": "522660", "category": "Mandal HQ"},
        {"town": "Pedakurapadu", "pincode": "522402", "category": "Mandal HQ & Constituency"},
        {"town": "Rajupalem (Palnadu)", "pincode": "522413", "category": "Mandal HQ"},
        {"town": "Rentachintala", "pincode": "522421", "category": "Mandal HQ"},
        {"town": "Savalyapuram", "pincode": "522646", "category": "Mandal HQ"},
        {"town": "Veldurthi (Palnadu)", "pincode": "522613", "category": "Mandal HQ"},
    ],
    "9. Tirupati District": [
        {"town": "Balayapalli", "pincode": "524404", "category": "Mandal HQ"},
        {"town": "Chillakur", "pincode": "524412", "category": "Mandal HQ & Industrial SEZ"},
        {"town": "Chittamuru", "pincode": "524415", "category": "Mandal HQ"},
        {"town": "Dakkili", "pincode": "524134", "category": "Mandal HQ"},
        {"town": "Doravarisatram", "pincode": "524123", "category": "Mandal HQ"},
        {"town": "Yerravaripalem", "pincode": "517190", "category": "Mandal HQ"},
        {"town": "Kota (Tirupati)", "pincode": "524411", "category": "Mandal HQ"},
        {"town": "Narayanavanam", "pincode": "517581", "category": "Mandal HQ & Heritage/Temple Town"},
        {"town": "Nindra", "pincode": "517591", "category": "Mandal HQ"},
        {"town": "Ojili", "pincode": "524402", "category": "Mandal HQ"},
        {"town": "Pakala", "pincode": "517112", "category": "Mandal HQ & Railway Junction"},
        {"town": "Pitchatur", "pincode": "517589", "category": "Mandal HQ"},
        {"town": "Renigunta", "pincode": "517520", "category": "Major Railway & Industrial Hub"},
        {"town": "Satyavedu", "pincode": "517588", "category": "Mandal HQ & Sri City SEZ Zone"},
        {"town": "Vadamalapeta", "pincode": "517551", "category": "Mandal HQ"},
        {"town": "Varadaiahpalem", "pincode": "517541", "category": "Mandal HQ & Sri City Hub"},
        {"town": "Vakadu", "pincode": "524415", "category": "Mandal HQ"},
    ],
    "10. Chittoor District": [
        {"town": "Baireddipalle", "pincode": "517415", "category": "Mandal HQ"},
        {"town": "Gudupalle", "pincode": "517425", "category": "Mandal HQ & Border Station"},
        {"town": "Gangadhara Nellore", "pincode": "517125", "category": "Mandal HQ & Assembly Constituency"},
        {"town": "Irala", "pincode": "517130", "category": "Mandal HQ & Mango Processing Hub"},
        {"town": "Karvetinagar", "pincode": "517419", "category": "Mandal HQ & Royal Palace Town"},
        {"town": "Ramakuppam", "pincode": "517401", "category": "Mandal HQ"},
        {"town": "Santhipuram", "pincode": "517423", "category": "Mandal HQ"},
        {"town": "Somala", "pincode": "517257", "category": "Mandal HQ"},
        {"town": "SR Puram (Srirangarajapuram)", "pincode": "517167", "category": "Mandal HQ"},
        {"town": "Thavanampalle", "pincode": "517131", "category": "Mandal HQ & Jaggery Trade Hub"},
        {"town": "Vedurukuppam", "pincode": "517569", "category": "Mandal HQ"},
        {"town": "V.Kota (Venkatagirikota)", "pincode": "517424", "category": "Mandal HQ & Major Border Trade Center"},
        {"town": "Vijayapuram", "pincode": "517586", "category": "Mandal HQ"},
        {"town": "Yadamari", "pincode": "517422", "category": "Mandal HQ"},
    ],
    "11. Annamayya District": [
        {"town": "Angallu", "pincode": "517325", "category": "Major Commercial Junction & College Hub"},
        {"town": "Chinnamandem", "pincode": "516214", "category": "Mandal HQ"},
        {"town": "Chitvel", "pincode": "516104", "category": "Mandal HQ"},
        {"town": "Galiveedu", "pincode": "516267", "category": "Mandal HQ"},
        {"town": "Gurramkonda", "pincode": "517297", "category": "Mandal HQ & Fort/Commercial Town"},
        {"town": "Kalakada", "pincode": "517235", "category": "Mandal HQ"},
        {"town": "Kambhamvaripalle (KV Palle)", "pincode": "517247", "category": "Mandal HQ"},
        {"town": "Lakkireddypalle", "pincode": "516257", "category": "Mandal HQ"},
        {"town": "Nandalur", "pincode": "516150", "category": "Mandal HQ & Railway Heritage Town"},
        {"town": "Nimmanapalle", "pincode": "517328", "category": "Mandal HQ & Tomato Trade Hub"},
        {"town": "Obulavaripalle", "pincode": "516108", "category": "Mandal HQ & Mineral Zone"},
        {"town": "Penagalur", "pincode": "516127", "category": "Mandal HQ"},
        {"town": "Pullampeta", "pincode": "516123", "category": "Mandal HQ"},
        {"town": "Ramapuram", "pincode": "516167", "category": "Mandal HQ"},
        {"town": "Sambepalle", "pincode": "516215", "category": "Mandal HQ"},
        {"town": "T Sundupalle", "pincode": "516130", "category": "Mandal HQ"},
        {"town": "Veeraballi", "pincode": "516268", "category": "Mandal HQ"},
    ],
    "12. YSR Kadapa District": [
        {"town": "Atlur", "pincode": "516107", "category": "Mandal HQ"},
        {"town": "Chennur (Kadapa)", "pincode": "516162", "category": "Mandal HQ & Suburban Hub"},
        {"town": "CK Dinne (Chinthakommadinne)", "pincode": "516003", "category": "Peri-Urban Kadapa Hub"},
        {"town": "Gopavaram", "pincode": "516163", "category": "Mandal HQ"},
        {"town": "Khajipet", "pincode": "516269", "category": "Mandal HQ"},
        {"town": "Kondapuram (Kadapa)", "pincode": "516444", "category": "Mandal HQ"},
        {"town": "Lingala", "pincode": "516396", "category": "Mandal HQ & Uranium/Mining Zone"},
        {"town": "Muddanur", "pincode": "516380", "category": "Mandal HQ & Railway/Cement Town"},
        {"town": "Pendlimarri", "pincode": "516216", "category": "Mandal HQ"},
        {"town": "Porumamilla", "pincode": "516193", "category": "Mandal HQ & Major Commercial Town"},
        {"town": "Simhadripuram", "pincode": "516454", "category": "Mandal HQ"},
        {"town": "Thondur", "pincode": "516401", "category": "Mandal HQ"},
        {"town": "Vallur", "pincode": "516293", "category": "Mandal HQ"},
        {"town": "VN Palle (Veerapunayunipalle)", "pincode": "516321", "category": "Mandal HQ"},
        {"town": "Vontimitta", "pincode": "516151", "category": "Mandal HQ & Temple Heritage Town"},
    ],
    "13. Sri Potti Sriramulu Nellore District": [
        {"town": "Allur", "pincode": "524315", "category": "Mandal HQ & Coastal Market"},
        {"town": "Ananthasagaram", "pincode": "524302", "category": "Mandal HQ"},
        {"town": "AS Pet (Anamasamudrampet)", "pincode": "524304", "category": "Mandal HQ & Pilgrim Town"},
        {"town": "Bogole", "pincode": "524142", "category": "Mandal HQ"},
        {"town": "Chejerla", "pincode": "524305", "category": "Mandal HQ"},
        {"town": "Dagadarthi", "pincode": "524240", "category": "Mandal HQ & Proposed Airport Zone"},
        {"town": "Duttalur", "pincode": "524222", "category": "Mandal HQ"},
        {"town": "Indukurpet", "pincode": "524314", "category": "Mandal HQ & Aquaculture Belt"},
        {"town": "Kaligiri", "pincode": "524224", "category": "Mandal HQ"},
        {"town": "Kaluvoya", "pincode": "524342", "category": "Mandal HQ"},
        {"town": "Kodavaluru", "pincode": "524316", "category": "Mandal HQ & Highway/Industrial Hub"},
        {"town": "Kondapuram (Nellore)", "pincode": "524239", "category": "Mandal HQ"},
        {"town": "Manubolu", "pincode": "524405", "category": "Mandal HQ & Highway Town"},
        {"town": "Marripadu", "pincode": "524312", "category": "Mandal HQ"},
        {"town": "Podalakuru", "pincode": "524345", "category": "Mandal HQ & Commercial Town"},
        {"town": "Rapur", "pincode": "524408", "category": "Mandal HQ & Mica/Forest Belt"},
        {"town": "Sangam", "pincode": "524308", "category": "Mandal HQ & River Barrage Hub"},
        {"town": "Seetharamapuram", "pincode": "524226", "category": "Mandal HQ"},
        {"town": "Thotapalligudur", "pincode": "524311", "category": "Mandal HQ"},
        {"town": "Vidavaluru", "pincode": "524318", "category": "Mandal HQ"},
        {"town": "Vinjamuru", "pincode": "524228", "category": "Mandal HQ & Trade Hub"},
    ],
    "14. Prakasam District": [
        {"town": "Ardhaveedu", "pincode": "523335", "category": "Mandal HQ"},
        {"town": "CS Puram (Chandrasekarapuram)", "pincode": "523112", "category": "Mandal HQ"},
        {"town": "Bestavaripeta", "pincode": "523333", "category": "Mandal HQ"},
        {"town": "Cumbum", "pincode": "523333", "category": "Mandal HQ & Historic Railway/Lake Town"},
        {"town": "Donakonda", "pincode": "523305", "category": "Mandal HQ & Industrial/Airport Zone"},
        {"town": "HM Padu (Hanumanthunipeta)", "pincode": "523227", "category": "Mandal HQ"},
        {"town": "Komarolu", "pincode": "523373", "category": "Mandal HQ"},
        {"town": "Konakanamitla", "pincode": "523241", "category": "Mandal HQ"},
        {"town": "Kothapatnam", "pincode": "523186", "category": "Mandal HQ & Coastal Tourism Zone"},
        {"town": "Kurichedu", "pincode": "523304", "category": "Mandal HQ"},
        {"town": "Maddipadu", "pincode": "523211", "category": "Mandal HQ & Highway/Granite Belt"},
        {"town": "Marripudi", "pincode": "523270", "category": "Mandal HQ"},
        {"town": "NG Padu (Naguluppalapadu)", "pincode": "523183", "category": "Mandal HQ"},
        {"town": "Pamuru", "pincode": "523108", "category": "Mandal HQ & Major Commercial Town"},
        {"town": "PC Palle (Pedacherlopalle)", "pincode": "523111", "category": "Mandal HQ"},
        {"town": "Peddaraveedu", "pincode": "523320", "category": "Mandal HQ"},
        {"town": "Pullalacheruvu", "pincode": "523328", "category": "Mandal HQ"},
        {"town": "Racherla", "pincode": "523368", "category": "Mandal HQ"},
        {"town": "SN Padu (Santhanuthalapadu)", "pincode": "523225", "category": "Mandal HQ & Assembly Constituency"},
        {"town": "Tarlupadu", "pincode": "523332", "category": "Mandal HQ"},
        {"town": "Tanguturu", "pincode": "523274", "category": "Mandal HQ & Tobacco/Granite Center"},
        {"town": "Tripuranthakam", "pincode": "523326", "category": "Mandal HQ & Temple Gateway Town"},
        {"town": "Veligandla", "pincode": "523224", "category": "Mandal HQ"},
        {"town": "Voletivaripalem", "pincode": "523116", "category": "Mandal HQ"},
    ],
    "15. Kurnool District": [
        {"town": "C.Belagal", "pincode": "518008", "category": "Mandal HQ"},
        {"town": "Devanakonda", "pincode": "518465", "category": "Mandal HQ"},
        {"town": "Gospadu", "pincode": "518674", "category": "Mandal HQ"},
        {"town": "Gudur (Kurnool)", "pincode": "518510", "category": "Mandal HQ & Industrial Suburb"},
        {"town": "Holagunda", "pincode": "518346", "category": "Mandal HQ"},
        {"town": "Kallur (Kurnool Urban)", "pincode": "518003", "category": "Major Urban Commercial Zone"},
        {"town": "Kowthalam", "pincode": "518344", "category": "Mandal HQ"},
        {"town": "Krishnagiri", "pincode": "518222", "category": "Mandal HQ"},
        {"town": "Orvakal", "pincode": "518010", "category": "Mandal HQ & Industrial/Airport Hub"},
        {"town": "Maddikera", "pincode": "518385", "category": "Mandal HQ & Railway Junction"},
        {"town": "Pedda Kadabur", "pincode": "518323", "category": "Mandal HQ"},
        {"town": "Tuggali", "pincode": "518390", "category": "Mandal HQ & Gold Mining Belt"},
        {"town": "Veldurthi (Kurnool)", "pincode": "518216", "category": "Mandal HQ & Iron Ore Trade Hub"},
    ],
    "16. Nandyal District": [
        {"town": "Chagalamarri", "pincode": "518553", "category": "Mandal HQ & Border Market Town"},
        {"town": "Dornipadu", "pincode": "518543", "category": "Mandal HQ"},
        {"town": "Gadivemula", "pincode": "518508", "category": "Mandal HQ"},
        {"town": "Jupadu Bungalow", "pincode": "518401", "category": "Mandal HQ"},
        {"town": "Kolimigundla", "pincode": "518123", "category": "Mandal HQ & Cement Industry Hub"},
        {"town": "Kothapalle (Nandyal)", "pincode": "518401", "category": "Mandal HQ"},
        {"town": "Mahanandi", "pincode": "518502", "category": "Mandal HQ & Famous Temple Town"},
        {"town": "Midthur", "pincode": "518405", "category": "Mandal HQ"},
        {"town": "Owk", "pincode": "518122", "category": "Mandal HQ & Reservoir/Palace Town"},
        {"town": "Pagidyala", "pincode": "518412", "category": "Mandal HQ"},
        {"town": "Pamulapadu", "pincode": "518442", "category": "Mandal HQ"},
        {"town": "Peapully", "pincode": "518221", "category": "Mandal HQ & NH-44 Commercial Hub"},
        {"town": "Rudravaram", "pincode": "518594", "category": "Mandal HQ"},
        {"town": "Sirvel", "pincode": "518563", "category": "Mandal HQ & Commercial Market"},
        {"town": "Sanjamala", "pincode": "518145", "category": "Mandal HQ"},
        {"town": "Velgodu", "pincode": "518533", "category": "Mandal HQ & Reservoir Town"},
    ],
    "17. Anantapur District": [
        {"town": "Atmakur (Anantapur)", "pincode": "515751", "category": "Mandal HQ"},
        {"town": "Beluguppa", "pincode": "515741", "category": "Mandal HQ"},
        {"town": "Bommanahal", "pincode": "515863", "category": "Mandal HQ & Border Town"},
        {"town": "Brahmasamudram", "pincode": "515763", "category": "Mandal HQ"},
        {"town": "BR Samudram (Bukkarayasamudram)", "pincode": "515701", "category": "Mandal HQ & Peri-Urban Hub"},
        {"town": "D.Hirehal", "pincode": "515872", "category": "Mandal HQ & Mining/Border Zone"},
        {"town": "Garladinne", "pincode": "515731", "category": "Mandal HQ & NH-44 Town"},
        {"town": "Gummagatta", "pincode": "515865", "category": "Mandal HQ"},
        {"town": "Kambadur", "pincode": "515765", "category": "Mandal HQ"},
        {"town": "Kanekal", "pincode": "515871", "category": "Mandal HQ & Commercial Market"},
        {"town": "Kudair", "pincode": "515762", "category": "Mandal HQ"},
        {"town": "Narpala", "pincode": "515425", "category": "Mandal HQ"},
        {"town": "Peddapappur", "pincode": "515445", "category": "Mandal HQ"},
        {"town": "Peddavaduguru", "pincode": "515405", "category": "Mandal HQ"},
        {"town": "Putlur", "pincode": "515414", "category": "Mandal HQ"},
        {"town": "Rapthadu", "pincode": "515731", "category": "Mandal HQ & Assembly Constituency"},
        {"town": "Settur", "pincode": "515767", "category": "Mandal HQ"},
        {"town": "Vajrakarur", "pincode": "515840", "category": "Mandal HQ & Diamond Mining Belt"},
        {"town": "Vidapanakal", "pincode": "515870", "category": "Mandal HQ"},
        {"town": "Yellanur", "pincode": "515465", "category": "Mandal HQ"},
    ],
    "18. Sri Sathya Sai District": [
        {"town": "Agali", "pincode": "515311", "category": "Mandal HQ & Border Town"},
        {"town": "Amadagur", "pincode": "515556", "category": "Mandal HQ"},
        {"town": "Amarapuram", "pincode": "515281", "category": "Mandal HQ"},
        {"town": "Bathalapalle", "pincode": "515661", "category": "Mandal HQ & Hospital/Highway Town"},
        {"town": "CK Palle (Chennekothapalle)", "pincode": "515101", "category": "Mandal HQ"},
        {"town": "Chilamathur", "pincode": "515341", "category": "Mandal HQ & Border Industrial Park"},
        {"town": "Gandlapenta", "pincode": "515521", "category": "Mandal HQ"},
        {"town": "Gudibanda", "pincode": "515271", "category": "Mandal HQ"},
        {"town": "Kanaganapalle", "pincode": "515101", "category": "Mandal HQ & NH-44 Town"},
        {"town": "Kothacheruvu", "pincode": "515133", "category": "Mandal HQ & High-Growth Suburb"},
        {"town": "Nallacheruvu", "pincode": "515551", "category": "Mandal HQ"},
        {"town": "Nallamada", "pincode": "515541", "category": "Mandal HQ"},
        {"town": "ODC (Obuladevaracheruvu)", "pincode": "515561", "category": "Mandal HQ"},
        {"town": "Parigi (SSS District)", "pincode": "515261", "category": "Mandal HQ"},
        {"town": "Ramagiri", "pincode": "515101", "category": "Mandal HQ & Gold Mine Belt"},
        {"town": "Roddam", "pincode": "515123", "category": "Mandal HQ"},
        {"town": "Rolla", "pincode": "515321", "category": "Mandal HQ"},
        {"town": "Somandepalle", "pincode": "515122", "category": "Mandal HQ & Railway Junction"},
        {"town": "Talupula", "pincode": "515531", "category": "Mandal HQ"},
        {"town": "Tanakal", "pincode": "515561", "category": "Mandal HQ"},
    ],
    "19. East Godavari District": [
        {"town": "Biccavolu", "pincode": "533343", "category": "Mandal HQ & Heritage Temple Town"},
        {"town": "Chagallu", "pincode": "534342", "category": "Mandal HQ & Sugar Industry Town"},
        {"town": "Devarapalli (East Godavari)", "pincode": "534313", "category": "Mandal HQ"},
        {"town": "Gokavaram", "pincode": "533286", "category": "Mandal HQ & Trade Hub"},
        {"town": "Korukonda", "pincode": "533289", "category": "Mandal HQ & Pilgrim Center"},
        {"town": "Peravali", "pincode": "534328", "category": "Mandal HQ & Highway Junction"},
        {"town": "Seethanagaram (East Godavari)", "pincode": "533287", "category": "Mandal HQ"},
        {"town": "Tallapudi", "pincode": "534341", "category": "Mandal HQ"},
        {"town": "Undrajavaram", "pincode": "534342", "category": "Mandal HQ"},
    ],
    "20. Kakinada District": [
        {"town": "Gollaprolu", "pincode": "533445", "category": "Mandal HQ & Saree/Agricultural Market"},
        {"town": "Kajuluru", "pincode": "533468", "category": "Mandal HQ"},
        {"town": "Karapa", "pincode": "533008", "category": "Mandal HQ & Peri-Urban Hub"},
        {"town": "Kirlampudi", "pincode": "533431", "category": "Mandal HQ"},
        {"town": "Kotananduru", "pincode": "533407", "category": "Mandal HQ"},
        {"town": "Pedapudi", "pincode": "533008", "category": "Mandal HQ"},
        {"town": "Sankhavaram", "pincode": "533446", "category": "Mandal HQ"},
        {"town": "Thondangi", "pincode": "533408", "category": "Mandal HQ & Port SEZ Belt"},
        {"town": "Tallarevu", "pincode": "533463", "category": "Mandal HQ & Industrial/Aquaculture Hub"},
        {"town": "U.Kothapalli", "pincode": "533448", "category": "Mandal HQ & Beach/Port Zone"},
    ],
    "21. Dr. B.R. Ambedkar Konaseema District": [
        {"town": "Ainavilli", "pincode": "533211", "category": "Mandal HQ & Temple Town"},
        {"town": "Allavaram", "pincode": "533217", "category": "Mandal HQ & Coconut Trade Center"},
        {"town": "Ambajipeta", "pincode": "533214", "category": "Mandal HQ & Major Coconut Market"},
        {"town": "Atreyapuram", "pincode": "533235", "category": "Mandal HQ & Pootharekulu Sweet Town"},
        {"town": "I.Polavaram", "pincode": "533214", "category": "Mandal HQ"},
        {"town": "Kapileswarapuram", "pincode": "533309", "category": "Mandal HQ"},
        {"town": "Katrenikona", "pincode": "533212", "category": "Mandal HQ & Aquaculture Belt"},
        {"town": "Malikipuram", "pincode": "533253", "category": "Mandal HQ & ONGC Industrial Hub"},
        {"town": "P.Gannavaram", "pincode": "533240", "category": "Mandal HQ & Aqueduct Town"},
        {"town": "Rayavaram", "pincode": "533346", "category": "Mandal HQ"},
        {"town": "Sakhinetipalle", "pincode": "533251", "category": "Mandal HQ & Coastal Resort Zone"},
        {"town": "Uppalaguptam", "pincode": "533222", "category": "Mandal HQ"},
    ],
    "22. West Godavari District": [
        {"town": "Akividu", "pincode": "534235", "category": "Mandal HQ & Major Aqua Export Hub"},
        {"town": "Attili", "pincode": "534134", "category": "Mandal HQ & Rice Mill Hub"},
        {"town": "Iragavaram", "pincode": "534320", "category": "Mandal HQ"},
        {"town": "Kalla", "pincode": "534237", "category": "Mandal HQ & Aquaculture Zone"},
        {"town": "Mogalthur", "pincode": "534281", "category": "Mandal HQ & Coastal/Aqua Belt"},
        {"town": "Palacoderu", "pincode": "534210", "category": "Mandal HQ"},
        {"town": "Penugonda", "pincode": "534320", "category": "Mandal HQ & Commercial Market"},
        {"town": "Penumantra", "pincode": "534124", "category": "Mandal HQ"},
        {"town": "Poduru", "pincode": "534134", "category": "Mandal HQ"},
        {"town": "Veeravasaram", "pincode": "534245", "category": "Mandal HQ"},
        {"town": "Yelamanchili (West Godavari)", "pincode": "534327", "category": "Mandal HQ"},
    ],
    "23. Eluru District": [
        {"town": "Agiripalli", "pincode": "521211", "category": "Mandal HQ & Suburban Hub"},
        {"town": "Bhimadole", "pincode": "534380", "category": "Mandal HQ & Highway/Railway Junction"},
        {"town": "Buttayagudem", "pincode": "534447", "category": "Mandal HQ"},
        {"town": "Chatrai", "pincode": "521214", "category": "Mandal HQ"},
        {"town": "Denduluru", "pincode": "534432", "category": "Mandal HQ"},
        {"town": "Jeelugumilli", "pincode": "534456", "category": "Mandal HQ & Cashew/Forest Belt"},
        {"town": "Koyyalagudem", "pincode": "534312", "category": "Mandal HQ & Major Trade Center"},
        {"town": "Lingapalem", "pincode": "534462", "category": "Mandal HQ"},
        {"town": "Musunuru", "p21207": "521207", "pincode": "521207", "category": "Mandal HQ & Mango Belt"},
        {"town": "Nidamarru", "pincode": "534401", "category": "Mandal HQ"},
        {"town": "Pedapadu", "pincode": "534437", "category": "Mandal HQ"},
        {"town": "Pedavegi", "pincode": "534435", "category": "Mandal HQ & Heritage Site"},
        {"town": "Polavaram", "pincode": "534315", "category": "Mandal HQ & National Project Hub"},
        {"town": "T.Narasapuram", "pincode": "534461", "category": "Mandal HQ"},
        {"town": "Unguturu (Eluru)", "pincode": "534411", "category": "Mandal HQ & Highway Town"},
    ],
    "24. Srikakulam District": [
        {"town": "Bhamini", "pincode": "532456", "category": "Mandal HQ"},
        {"town": "Burja", "pincode": "532445", "category": "Mandal HQ"},
        {"town": "Gara", "pincode": "532405", "category": "Mandal HQ & Kalingapatnam Beach Hub"},
        {"town": "Hiramandalam", "pincode": "532459", "category": "Mandal HQ & Reservoir Town"},
        {"town": "Jalumuru", "pincode": "532432", "category": "Mandal HQ"},
        {"town": "Kanchili", "pincode": "532290", "category": "Mandal HQ & Cashew Belt"},
        {"town": "Kothuru (Srikakulam)", "pincode": "532455", "category": "Mandal HQ"},
        {"town": "LN Peta (Laxminarsupeta)", "pincode": "532458", "category": "Mandal HQ"},
        {"town": "Mandasa", "pincode": "532242", "category": "Mandal HQ & Heritage Palace Town"},
        {"town": "Meliaputti", "pincode": "532215", "category": "Mandal HQ"},
        {"town": "Nandigam (Srikakulam)", "pincode": "532204", "category": "Mandal HQ"},
        {"town": "Polaki", "pincode": "532429", "category": "Mandal HQ"},
        {"town": "Ponduru", "pincode": "532168", "category": "Mandal HQ & Famous Khadi Hub"},
        {"town": "Ranasthalam", "pincode": "532407", "category": "Mandal HQ & Industrial Park Zone"},
        {"town": "Sarubujjili", "pincode": "532458", "category": "Mandal HQ"},
        {"town": "Seethampeta", "pincode": "532440", "category": "Mandal HQ & ITDA Agency Center"},
        {"town": "Vajrapukotturu", "pincode": "532220", "category": "Mandal HQ & Salt/Cashew Belt"},
        {"town": "Vangara", "pincode": "532461", "category": "Mandal HQ"},
    ],
    "25. Vizianagaram District": [
        {"town": "Badangi", "pincode": "535557", "category": "Mandal HQ"},
        {"town": "Bhoghapuram", "pincode": "535216", "category": "Mandal HQ & International Airport Zone"},
        {"town": "Bondapalli", "pincode": "535260", "category": "Mandal HQ"},
        {"town": "Dattirajeru", "pincode": "535580", "category": "Mandal HQ"},
        {"town": "Denkada", "pincode": "535005", "category": "Mandal HQ & Education Zone"},
        {"town": "Gantyada", "pincode": "535215", "category": "Mandal HQ"},
        {"town": "Garividi", "pincode": "535101", "category": "Mandal HQ & Manganese Industry Hub"},
        {"town": "Gurla", "pincode": "535217", "category": "Mandal HQ"},
        {"town": "Jami", "pincode": "535250", "category": "Mandal HQ"},
        {"town": "L.Kota (Lakkavarapukota)", "pincode": "535240", "category": "Mandal HQ"},
        {"town": "Mentada", "pincode": "535273", "category": "Mandal HQ"},
        {"town": "Merakamudidam", "pincode": "535102", "category": "Mandal HQ"},
        {"town": "Pusapatirega", "pincode": "535204", "category": "Mandal HQ & Industrial Coastal Belt"},
        {"town": "Ramabhadrapuram", "pincode": "535579", "category": "Mandal HQ & Highway Market Hub"},
        {"town": "Therlam", "pincode": "535126", "category": "Mandal HQ"},
        {"town": "Vepada", "pincode": "535281", "category": "Mandal HQ"},
    ],
    "26. Parvathipuram Manyam District": [
        {"town": "Balajipeta", "pincode": "535558", "category": "Mandal HQ"},
        {"town": "Garugubilli", "pincode": "535463", "category": "Mandal HQ"},
        {"town": "GL Puram (Gummalaxmipuram)", "pincode": "535523", "category": "Mandal HQ & ITDA Tribal Center"},
        {"town": "Jiapeta (Jiammapeta)", "pincode": "535525", "category": "Mandal HQ"},
        {"town": "Komarada", "pincode": "535521", "category": "Mandal HQ & Railway Station Town"},
        {"town": "Makkuva", "pincode": "535547", "category": "Mandal HQ"},
        {"town": "Pachipenta", "pincode": "535592", "category": "Mandal HQ"},
        {"town": "Veeraghattam", "pincode": "532460", "category": "Mandal HQ & Commercial Market"},
    ]
}

total_ap_missing = sum(len(towns) for towns in AP_MISSING_TOWNS_BY_DISTRICT.values())
print(f"Total Uncovered Andhra Pradesh Towns & Mandals Identified: {total_ap_missing}")
