import json

TELANGANA_MISSING_TOWNS_BY_DISTRICT = {
    "1. Hyderabad District": [
        {"town": "Himayatnagar", "pincode": "500029", "category": "Major Commercial Hub"},
        {"town": "Punjagutta", "pincode": "500082", "category": "Commercial & Medical Hub"},
        {"town": "Somajiguda", "pincode": "500082", "category": "Corporate & Hospital Zone"},
        {"town": "Koti", "pincode": "500095", "category": "Wholesale Cosmetic Market"},
        {"town": "Amberpet", "pincode": "500013", "category": "Mandal HQ & Assembly Constituency"},
        {"town": "Musheerabad", "pincode": "500020", "category": "Commercial Hub & Constituency"},
        {"town": "Sanathnagar", "pincode": "500018", "category": "Industrial & Retail Hub"},
        {"town": "Goshamahal", "pincode": "500012", "category": "Wholesale Trade Hub"},
        {"town": "Chandrayangutta", "pincode": "500005", "category": "South Zone Retail Hub"},
        {"town": "Yakutpura", "pincode": "500023", "category": "Old City Retail Hub"},
        {"town": "Bahadurpura", "pincode": "500064", "category": "Commercial & Zoo Zone"},
        {"town": "Santoshnagar", "pincode": "500059", "category": "Residential & Business Hub"},
        {"town": "Falaknuma", "pincode": "500053", "category": "Historical & Retail Zone"},
        {"town": "Saidabad", "pincode": "500059", "category": "Mandal HQ & Business Hub"},
        {"town": "Moosapet", "pincode": "500018", "category": "Commercial Hub"},
        {"town": "SR Nagar (Sanjeeva Reddy Nagar)", "pincode": "500038", "category": "Commercial & Coaching Hub"},
        {"town": "Narayanaguda", "pincode": "500029", "category": "Retail & Education Hub"},
        {"town": "Chikkadpally", "pincode": "500020", "category": "Commercial & Cultural Hub"},
    ],
    "2. Medchal-Malkajgiri District": [
        {"town": "Kapra (Uppal Kalan)", "pincode": "500062", "category": "Major Residential & Retail Hub"},
        {"town": "Bachupally", "pincode": "500090", "category": "Education & High-rise Retail Hub"},
        {"town": "Nizampet", "pincode": "500090", "category": "Dense Residential & Commercial Zone"},
        {"town": "Dundigal", "pincode": "500043", "category": "Mandal HQ & Industrial Zone"},
        {"town": "Shamirpet", "pincode": "501701", "category": "Mandal HQ & Knowledge Corridor"},
        {"town": "Medipally", "pincode": "500098", "category": "Mandal HQ & Highway Retail Corridor"},
        {"town": "Boduppal", "pincode": "500092", "category": "Municipal Corporation & Retail Hub"},
        {"town": "Peerzadiguda", "pincode": "500039", "category": "Municipal Corporation & Commercial Hub"},
        {"town": "Jawaharnagar", "pincode": "500087", "category": "Municipal Corporation"},
        {"town": "Cherlapally", "pincode": "500051", "category": "Industrial & Wholesale Zone"},
        {"town": "Moula Ali", "pincode": "500040", "category": "Commercial & Railway Hub"},
    ],
    "3. Rangareddy District": [
        {"town": "Hayathnagar", "pincode": "501505", "category": "Mandal HQ & Highway Market Hub"},
        {"town": "Vanasthalipuram", "pincode": "500070", "category": "Major Retail & Commercial Hub"},
        {"town": "Pedda Amberpet", "pincode": "501505", "category": "Municipality & Commercial Zone"},
        {"town": "Manikonda", "pincode": "500089", "category": "IT Corridor High-Density Hub"},
        {"town": "Narsingi", "pincode": "500075", "category": "Municipality & Commercial Hub"},
        {"town": "Bandlaguda Jagir", "pincode": "500086", "category": "Municipal Corporation"},
        {"town": "Moinabad", "pincode": "501504", "category": "Mandal HQ & Institutional Hub"},
        {"town": "Shabad", "pincode": "509217", "category": "Mandal HQ & Industrial Park"},
        {"town": "Kothur", "pincode": "509228", "category": "Mandal HQ & Industrial/Commercial Town"},
        {"town": "Kandukur", "pincode": "501359", "category": "Mandal HQ & Pharma City Zone"},
        {"town": "Yacharam", "pincode": "501509", "category": "Mandal HQ"},
        {"town": "Manchal", "pincode": "501508", "category": "Mandal HQ"},
        {"town": "Amangal", "pincode": "509321", "category": "Mandal HQ & Commercial Town"},
        {"town": "Madgul", "pincode": "509327", "category": "Mandal HQ"},
        {"town": "Kadthal", "pincode": "509358", "category": "Mandal HQ & Highway Town"},
    ],
    "4. Hanamkonda (Warangal Urban) District": [
        {"town": "Bheemadevarapally", "pincode": "505471", "category": "Mandal HQ"},
        {"town": "Elkaturthy", "pincode": "505469", "category": "Mandal HQ & Highway Hub"},
        {"town": "Inavolu", "pincode": "506143", "category": "Mandal HQ & Temple Town"},
        {"town": "Kamalapur", "pincode": "505102", "category": "Mandal HQ"},
        {"town": "Velair", "pincode": "506142", "category": "Mandal HQ"},
    ],
    "5. Warangal District": [
        {"town": "Atmakur (Warangal)", "pincode": "506342", "category": "Mandal HQ"},
        {"town": "Chennaraopet", "pincode": "506332", "category": "Mandal HQ"},
        {"town": "Duggondi", "pincode": "506331", "category": "Mandal HQ"},
        {"town": "Geesugonda", "pincode": "506330", "category": "Mandal HQ & Textile Park Zone"},
        {"town": "Khanapur (Warangal)", "pincode": "506132", "category": "Mandal HQ"},
        {"town": "Nekkonda", "pincode": "506122", "category": "Mandal HQ & Railway Station Town"},
        {"town": "Parvathagiri", "pincode": "506365", "category": "Mandal HQ"},
        {"town": "Rayaparthy", "pincode": "506314", "category": "Mandal HQ"},
        {"town": "Sangem", "pincode": "506329", "category": "Mandal HQ"},
    ],
    "6. Khammam District": [
        {"town": "Chintakani", "pincode": "507208", "category": "Mandal HQ & Railway Junction"},
        {"town": "Khammam Rural", "pincode": "507002", "category": "Peri-Urban Commercial Belt"},
        {"town": "Konijerla", "pincode": "507165", "category": "Mandal HQ"},
        {"town": "Mudigonda", "pincode": "507158", "category": "Mandal HQ"},
        {"town": "Raghunadhapalem", "pincode": "507002", "category": "Suburban Khammam Hub"},
        {"town": "Singareni (Kamepalli)", "pincode": "507122", "category": "Mandal HQ & Mining Town"},
        {"town": "Tallada", "pincode": "507167", "category": "Mandal HQ & Highway Commercial Hub"},
        {"town": "Vemsoor", "pincode": "507164", "category": "Mandal HQ"},
    ],
    "7. Bhadradri Kothagudem District": [
        {"town": "Chandrugonda", "pincode": "507116", "category": "Mandal HQ"},
        {"town": "Cherla", "pincode": "507137", "category": "Mandal HQ & Border Town"},
        {"town": "Allapalli", "pincode": "507124", "category": "Mandal HQ"},
        {"town": "Annapureddypally", "pincode": "507116", "category": "Mandal HQ"},
        {"town": "Mulakalapally", "pincode": "507115", "category": "Mandal HQ"},
        {"town": "Tekulapally", "pincode": "507123", "category": "Mandal HQ"},
        {"town": "Gundala (Bhadradri)", "pincode": "507123", "category": "Mandal HQ"},
        {"town": "Pinapaka", "pincode": "507117", "category": "Mandal HQ & Power Hub"},
        {"town": "Karakagudem", "pincode": "507117", "category": "Mandal HQ"},
        {"town": "Sujatanagar", "pincode": "507101", "category": "Mandal HQ"},
        {"town": "Laxmidevipalli", "pincode": "507101", "category": "Mandal HQ"},
        {"town": "Julurpad", "pincode": "507125", "category": "Mandal HQ"},
        {"town": "Dummugudem", "pincode": "507137", "category": "Mandal HQ & Historical Town"},
    ],
    "8. Karimnagar District": [
        {"town": "Gangadhara", "pincode": "505445", "category": "Mandal HQ"},
        {"town": "Ganneruvaram", "pincode": "505530", "category": "Mandal HQ"},
        {"town": "Kothapally (Karimnagar)", "pincode": "505451", "category": "Mandal HQ & Granite/Stone Hub"},
        {"town": "Ramadugu", "pincode": "505531", "category": "Mandal HQ"},
        {"town": "Saidapur", "pincode": "505472", "category": "Mandal HQ"},
        {"town": "Shankarapatnam (Kesavapatnam)", "pincode": "505470", "category": "Mandal HQ & Highway Town"},
        {"town": "Thimmapur", "pincode": "505527", "category": "Mandal HQ"},
        {"town": "Chigurumamidi", "pincode": "505467", "category": "Mandal HQ"},
    ],
    "9. Peddapalli District": [
        {"town": "Anthergaon", "pincode": "505514", "category": "Mandal HQ"},
        {"town": "Dharmaram", "pincode": "505505", "category": "Mandal HQ"},
        {"town": "Eligaid", "pincode": "505525", "category": "Mandal HQ"},
        {"town": "Julapalli", "pincode": "505525", "category": "Mandal HQ"},
        {"town": "Kamanpur", "pincode": "505188", "category": "Mandal HQ"},
        {"town": "Mutharam", "pincode": "505184", "category": "Mandal HQ"},
        {"town": "Odela", "pincode": "505152", "category": "Mandal HQ & Temple Town"},
        {"town": "Palakurthi (Peddapalli)", "pincode": "505187", "category": "Mandal HQ"},
    ],
    "10. Jagtial District": [
        {"town": "Buggaram", "pincode": "505530", "category": "Mandal HQ"},
        {"town": "Gollapally", "pincode": "505532", "category": "Mandal HQ"},
        {"town": "Ibrahimpatnam (Jagtial)", "pincode": "505460", "category": "Mandal HQ"},
        {"town": "Kathalapur", "pincode": "505462", "category": "Mandal HQ"},
        {"town": "Kodimial", "pincode": "505501", "category": "Mandal HQ"},
        {"town": "Mallial", "pincode": "505452", "category": "Mandal HQ"},
        {"town": "Mallapur", "pincode": "505460", "category": "Mandal HQ"},
        {"town": "Medipally (Jagtial)", "pincode": "505453", "category": "Mandal HQ"},
        {"town": "Pegadapally", "pincode": "505532", "category": "Mandal HQ"},
        {"town": "Raikal", "pincode": "505460", "category": "Mandal HQ & Commercial Market"},
        {"town": "Sarangapur (Jagtial)", "pincode": "505454", "category": "Mandal HQ"},
        {"town": "Velgatoor", "pincode": "505526", "category": "Mandal HQ"},
    ],
    "11. Rajanna Sircilla District": [
        {"town": "Boinpalli", "pincode": "505524", "category": "Mandal HQ"},
        {"town": "Chandurthi", "pincode": "505403", "category": "Mandal HQ"},
        {"town": "Illanthakunta", "pincode": "505405", "category": "Mandal HQ"},
        {"town": "Konaraopet", "pincode": "505301", "category": "Mandal HQ"},
        {"town": "Mustabad", "pincode": "505303", "category": "Mandal HQ & Weaving Hub"},
        {"town": "Rudrangi", "pincode": "505403", "category": "Mandal HQ"},
        {"town": "Thangallapally", "pincode": "505305", "category": "Mandal HQ"},
    ],
    "12. Nizamabad District": [
        {"town": "Indalwai", "pincode": "503164", "category": "Mandal HQ & Tollway Hub"},
        {"town": "Jakranpally", "pincode": "503224", "category": "Mandal HQ"},
        {"town": "Kotagiri", "pincode": "503188", "category": "Mandal HQ"},
        {"town": "Makloor", "pincode": "503003", "category": "Mandal HQ"},
        {"town": "Morthad", "pincode": "503225", "category": "Mandal HQ & Commercial Market"},
        {"town": "Mugpal", "pincode": "503003", "category": "Mandal HQ"},
        {"town": "Nandipet", "pincode": "503212", "category": "Mandal HQ"},
        {"town": "Renjal", "pincode": "503235", "category": "Mandal HQ"},
        {"town": "Rudrur", "pincode": "503246", "category": "Mandal HQ & Ag Research Center"},
        {"town": "Sirikonda", "pincode": "503165", "category": "Mandal HQ"},
        {"town": "Velpur", "pincode": "503213", "category": "Mandal HQ & Commercial Center"},
        {"town": "Yedapally", "pincode": "503202", "category": "Mandal HQ"},
    ],
    "13. Kamareddy District": [
        {"town": "Bhiknoor", "pincode": "503101", "category": "Mandal HQ & Highway Town"},
        {"town": "Birkoor", "pincode": "503102", "category": "Mandal HQ"},
        {"town": "Gandhari", "pincode": "503114", "category": "Mandal HQ"},
        {"town": "Lingampet", "pincode": "503124", "category": "Mandal HQ"},
        {"town": "Machareddy", "pincode": "503111", "category": "Mandal HQ"},
        {"town": "Madnoor", "pincode": "503309", "category": "Mandal HQ & Border Hub"},
        {"town": "Nagireddypet", "pincode": "503108", "category": "Mandal HQ"},
        {"town": "Nasrullabad", "pincode": "503187", "category": "Mandal HQ"},
        {"town": "Pitlam", "pincode": "503310", "category": "Mandal HQ & Business Junction"},
        {"town": "Rajampet (Kamareddy)", "pincode": "503111", "category": "Mandal HQ"},
        {"town": "Sadashivnagar", "pincode": "503145", "category": "Mandal HQ & Highway Town"},
        {"town": "Tadwai (Kamareddy)", "pincode": "503120", "category": "Mandal HQ"},
    ],
    "14. Adilabad District": [
        {"town": "Bazarhatnoor", "pincode": "504304", "category": "Mandal HQ"},
        {"town": "Bela", "pincode": "504309", "category": "Mandal HQ & Cotton Trade Hub"},
        {"town": "Gadiguda", "pincode": "504311", "category": "Mandal HQ"},
        {"town": "Gudihatnoor", "pincode": "504308", "category": "Mandal HQ & Highway Junction"},
        {"town": "Inderavelly", "pincode": "504311", "category": "Mandal HQ & Major Tribal Market"},
        {"town": "Mavala", "pincode": "504001", "category": "Peri-Urban Adilabad Hub"},
        {"town": "Narnoor", "pincode": "504311", "category": "Mandal HQ"},
        {"town": "Neradigonda", "pincode": "504307", "category": "Mandal HQ & Highway Hub"},
        {"town": "Sirikonda (Adilabad)", "pincode": "504308", "category": "Mandal HQ"},
        {"town": "Tamsi", "pincode": "504312", "category": "Mandal HQ"},
    ],
    "15. Mancherial District": [
        {"town": "Bheemaram", "pincode": "504204", "category": "Mandal HQ"},
        {"town": "Jaipur (Mancherial)", "pincode": "504216", "category": "Mandal HQ & Power Plant Zone"},
        {"town": "Kasipet", "pincode": "504231", "category": "Mandal HQ & Mining Hub"},
        {"town": "Kotapally", "pincode": "504201", "category": "Mandal HQ"},
        {"town": "Naspur", "pincode": "504302", "category": "Municipality & Coal Belt"},
        {"town": "Nennel", "pincode": "504204", "category": "Mandal HQ"},
        {"town": "Thandur (Mancherial)", "pincode": "504272", "category": "Mandal HQ"},
        {"town": "Vemanpally", "pincode": "504214", "category": "Mandal HQ"},
    ],
    "16. Nirmal District": [
        {"town": "Basar", "pincode": "504101", "category": "Mandal HQ & Temple/University Town"},
        {"town": "Dasturabad", "pincode": "504203", "category": "Mandal HQ"},
        {"town": "Dilawarpur", "pincode": "504306", "category": "Mandal HQ"},
        {"town": "Kubeer", "pincode": "504103", "category": "Mandal HQ"},
        {"town": "Kuntala", "pincode": "504109", "category": "Mandal HQ & Waterfall Tourist Hub"},
        {"town": "Laxmanchanda", "pincode": "504310", "category": "Mandal HQ"},
        {"town": "Lokeshwaram", "pincode": "504104", "category": "Mandal HQ"},
        {"town": "Mamada", "pincode": "504310", "category": "Mandal HQ"},
        {"town": "Narsapur (G)", "pincode": "504106", "category": "Mandal HQ"},
        {"town": "Pembi", "pincode": "504203", "category": "Mandal HQ"},
        {"town": "Soan", "pincode": "504306", "category": "Mandal HQ & Godavari Bridge Hub"},
        {"town": "Tanur", "pincode": "504102", "category": "Mandal HQ"},
    ],
    "17. Kumuram Bheem Asifabad District": [
        {"town": "Bejjur", "pincode": "504299", "category": "Mandal HQ"},
        {"town": "Chintalamanepally", "pincode": "504299", "category": "Mandal HQ"},
        {"town": "Dahegaon", "pincode": "504273", "category": "Mandal HQ"},
        {"town": "Kouthala", "pincode": "504299", "category": "Mandal HQ & Cotton Hub"},
        {"town": "Kerameri", "pincode": "504293", "category": "Mandal HQ & Tribal Market"},
        {"town": "Lingapur", "pincode": "504293", "category": "Mandal HQ"},
        {"town": "Penchikalpet", "pincode": "504296", "category": "Mandal HQ"},
        {"town": "Sirpur-U", "pincode": "504293", "category": "Mandal HQ"},
        {"town": "Tiryani", "pincode": "504293", "category": "Mandal HQ"},
        {"town": "Wankidi", "pincode": "504295", "category": "Mandal HQ & Border Town"},
    ],
    "18. Nalgonda District": [
        {"town": "Anumula", "pincode": "508278", "category": "Mandal HQ"},
        {"town": "Chandampet", "pincode": "508248", "category": "Mandal HQ"},
        {"town": "Damaracherla", "pincode": "508357", "category": "Mandal HQ & Cement Industry Hub"},
        {"town": "Gurrampode", "pincode": "508256", "category": "Mandal HQ"},
        {"town": "Kattangoor", "pincode": "508205", "category": "Mandal HQ & NH-65 Junction"},
        {"town": "Marriguda", "pincode": "508245", "category": "Mandal HQ"},
        {"town": "Nidamanoor", "pincode": "508278", "category": "Mandal HQ & Rice Mill Hub"},
        {"town": "Peddavoora", "pincode": "508266", "category": "Mandal HQ"},
        {"town": "Shaligouraram", "pincode": "508210", "category": "Mandal HQ"},
        {"town": "Thipparthy", "pincode": "508247", "category": "Mandal HQ & Railway Station Town"},
        {"town": "Tripuraram", "pincode": "508207", "category": "Mandal HQ"},
        {"town": "Vemulapally", "pincode": "508217", "category": "Mandal HQ"},
    ],
    "19. Suryapet District": [
        {"town": "Ananthagiri", "pincode": "508206", "category": "Mandal HQ"},
        {"town": "Atmakur (S)", "pincode": "508221", "category": "Mandal HQ"},
        {"town": "Chivvemla", "pincode": "508213", "category": "Mandal HQ & NH-65 Hub"},
        {"town": "Arvapally (Jajjireddygudem)", "pincode": "508222", "category": "Mandal HQ"},
        {"town": "Maddirala", "pincode": "508280", "category": "Mandal HQ"},
        {"town": "Mellachervu", "pincode": "508246", "category": "Mandal HQ & Cement/Temple Hub"},
        {"town": "Mothey", "pincode": "508212", "category": "Mandal HQ"},
        {"town": "Munagala", "pincode": "508233", "category": "Mandal HQ & NH-65 Commercial Hub"},
        {"town": "Nadigudem", "pincode": "508234", "category": "Mandal HQ"},
        {"town": "Nuthankal", "pincode": "508221", "category": "Mandal HQ"},
        {"town": "Penpahad", "pincode": "508213", "category": "Mandal HQ"},
        {"town": "Phanigiri", "pincode": "508280", "category": "Heritage & Commercial Center"},
    ],
    "20. Yadadri Bhuvanagiri District": [
        {"town": "Addagudur", "pincode": "508277", "category": "Mandal HQ"},
        {"town": "Atmakur (M)", "pincode": "508111", "category": "Mandal HQ"},
        {"town": "Bommalaramaram", "pincode": "508126", "category": "Mandal HQ"},
        {"town": "Gundala (Yadadri)", "pincode": "508277", "category": "Mandal HQ"},
        {"town": "Rajapet", "pincode": "508105", "category": "Mandal HQ"},
        {"town": "Ramannapet", "pincode": "508113", "category": "Mandal HQ & Weaving/Market Town"},
        {"town": "Turkapally", "pincode": "508115", "category": "Mandal HQ"},
        {"town": "Valigonda", "pincode": "508112", "category": "Mandal HQ & Market Center"},
    ],
    "21. Mahabubnagar District": [
        {"town": "Addakal", "pincode": "509382", "category": "Mandal HQ & NH-44 Hub"},
        {"town": "Bhoothpur", "pincode": "509382", "category": "Mandal HQ & Highway Junction"},
        {"town": "C.C.Kunta (Chincholi)", "pincode": "509382", "category": "Mandal HQ"},
        {"town": "Gandeed", "pincode": "509337", "category": "Mandal HQ"},
        {"town": "Hanwada", "pincode": "509334", "category": "Mandal HQ"},
        {"town": "Koilkonda", "pincode": "509371", "category": "Mandal HQ"},
        {"town": "Midjil", "pincode": "509357", "category": "Mandal HQ"},
        {"town": "Rajapur", "pincode": "509357", "category": "Mandal HQ & Highway Town"},
    ],
    "22. Nagarkurnool District": [
        {"town": "Charakonda", "pincode": "509324", "category": "Mandal HQ"},
        {"town": "Lingal", "pincode": "509401", "category": "Mandal HQ"},
        {"town": "Padara", "pincode": "509326", "category": "Mandal HQ"},
        {"town": "Pentlavelli", "pincode": "509102", "category": "Mandal HQ"},
        {"town": "Tadoor", "pincode": "509209", "category": "Mandal HQ"},
        {"town": "Telkapally", "pincode": "509102", "category": "Mandal HQ"},
        {"town": "Thimmajipet", "pincode": "509406", "category": "Mandal HQ"},
        {"town": "Urkonda", "pincode": "509324", "category": "Mandal HQ"},
        {"town": "Veldanda", "pincode": "509360", "category": "Mandal HQ & Highway Town"},
    ],
    "23. Wanaparthy District": [
        {"town": "Amarchinta", "pincode": "509130", "category": "Mandal HQ & Weaving Center"},
        {"town": "Atmakur (Wanaparthy)", "pincode": "509131", "category": "Mandal HQ & Market Hub"},
        {"town": "Chinnambavi", "pincode": "509104", "category": "Mandal HQ"},
        {"town": "Gopalpet", "pincode": "509206", "category": "Mandal HQ"},
        {"town": "Madanapur", "pincode": "509110", "category": "Mandal HQ & Railway Station Town"},
        {"town": "Revally", "pincode": "509103", "category": "Mandal HQ"},
        {"town": "Srirangapur", "pincode": "509104", "category": "Mandal HQ & Temple Town"},
        {"town": "Weepangandla", "pincode": "509104", "category": "Mandal HQ"},
    ],
    "24. Jogulamba Gadwal District": [
        {"town": "Dharoor (Gadwal)", "pincode": "509125", "category": "Mandal HQ"},
        {"town": "Ghattu", "pincode": "509127", "category": "Mandal HQ"},
        {"town": "Kyatur", "pincode": "509152", "category": "Mandal HQ"},
        {"town": "Manopad", "pincode": "509128", "category": "Mandal HQ & Highway Town"},
        {"town": "Rajoli", "pincode": "509126", "category": "Mandal HQ & Weaving Hub"},
        {"town": "Undavelly", "pincode": "509153", "category": "Mandal HQ"},
        {"town": "Waddepally", "pincode": "509126", "category": "Mandal HQ"},
    ],
    "25. Narayanpet District": [
        {"town": "Damaragidda", "pincode": "509210", "category": "Mandal HQ"},
        {"town": "Dhanwada", "pincode": "509351", "category": "Mandal HQ"},
        {"town": "Krishna", "pincode": "509208", "category": "Mandal HQ & Railway Station Town"},
        {"town": "Maganoor", "pincode": "509208", "category": "Mandal HQ & Border Town"},
        {"town": "Marikal", "pincode": "509351", "category": "Mandal HQ & Highway Market Hub"},
        {"town": "Narva", "pincode": "509130", "category": "Mandal HQ"},
    ],
    "26. Siddipet District": [
        {"town": "Bejjanki", "pincode": "505528", "category": "Mandal HQ"},
        {"town": "Chinnakodur", "pincode": "502267", "category": "Mandal HQ"},
        {"town": "Dhoolmitta", "pincode": "506223", "category": "Mandal HQ"},
        {"town": "Jagdevpur", "pincode": "502281", "category": "Mandal HQ"},
        {"town": "Koheda", "pincode": "505476", "category": "Mandal HQ"},
        {"town": "Kondapak", "pincode": "502277", "category": "Mandal HQ & Rajiv Rahadari Hub"},
        {"town": "Markook", "pincode": "502279", "category": "Mandal HQ"},
        {"town": "Mirdoddi", "pincode": "502108", "category": "Mandal HQ"},
        {"town": "Mulug (Siddipet)", "pincode": "502279", "category": "Mandal HQ & Horticulture University Hub"},
        {"town": "Nangunoor", "pincode": "502280", "category": "Mandal HQ"},
        {"town": "Narayanraopet", "pincode": "502103", "category": "Mandal HQ"},
        {"town": "Raipole", "pincode": "502278", "category": "Mandal HQ"},
        {"town": "Thoguta", "pincode": "502372", "category": "Mandal HQ & Kaleshwaram Hub"},
    ],
    "27. Medak District": [
        {"town": "Chilipched", "pincode": "502269", "category": "Mandal HQ"},
        {"town": "Haveli Ghanpur", "pincode": "502110", "category": "Mandal HQ"},
        {"town": "Kowdipally", "pincode": "502316", "category": "Mandal HQ"},
        {"town": "Kulcharam", "pincode": "502381", "category": "Mandal HQ"},
        {"town": "Manoharabad", "pincode": "502336", "category": "Mandal HQ & Industrial Park Zone"},
        {"town": "Narsingi (Medak)", "pincode": "502248", "category": "Mandal HQ & Highway Town"},
        {"town": "Papannapet", "pincode": "502115", "category": "Mandal HQ"},
        {"town": "Regode", "pincode": "502290", "category": "Mandal HQ"},
        {"town": "Shankarampet (A)", "pincode": "502271", "category": "Mandal HQ"},
        {"town": "Shankarampet (R)", "pincode": "502249", "category": "Mandal HQ"},
        {"town": "Tekmal", "pincode": "502302", "category": "Mandal HQ"},
        {"town": "Yeldurthy", "pincode": "502274", "category": "Mandal HQ"},
    ],
    "28. Sangareddy District": [
        {"town": "Gummadidala", "pincode": "502313", "category": "Mandal HQ & Industrial Hub"},
        {"town": "Kandi", "pincode": "502285", "category": "Mandal HQ & IIT Hyderabad Zone"},
        {"town": "Kangti", "pincode": "502286", "category": "Mandal HQ"},
        {"town": "Kohir", "pincode": "502210", "category": "Mandal HQ & Red Gram Market"},
        {"town": "Kondapur (Sangareddy)", "pincode": "502295", "category": "Mandal HQ"},
        {"town": "Manoor", "pincode": "502286", "category": "Mandal HQ"},
        {"town": "Mogudampally", "pincode": "502221", "category": "Mandal HQ"},
        {"town": "Munipally", "pincode": "502345", "category": "Mandal HQ & Highway Hub"},
        {"town": "Nagalgidda", "pincode": "502286", "category": "Mandal HQ"},
        {"town": "Nyalkal", "pincode": "502256", "category": "Mandal HQ"},
        {"town": "Pulkal", "pincode": "502273", "category": "Mandal HQ"},
        {"town": "Raikode", "pincode": "502294", "category": "Mandal HQ"},
        {"town": "Sirgapoor", "pincode": "502287", "category": "Mandal HQ"},
        {"town": "Vatpally", "pincode": "502270", "category": "Mandal HQ"},
    ],
    "29. Vikarabad District": [
        {"town": "Bantwaram", "pincode": "501106", "category": "Mandal HQ"},
        {"town": "Basheerabad", "pincode": "501127", "category": "Mandal HQ & Stone Quarry Hub"},
        {"town": "Nawabpet (Vikarabad)", "pincode": "501111", "category": "Mandal HQ"},
        {"town": "Doma", "pincode": "501502", "category": "Mandal HQ"},
        {"town": "Doultabad", "pincode": "501359", "category": "Mandal HQ"},
        {"town": "Kulkacharla", "pincode": "501502", "category": "Mandal HQ"},
        {"town": "Marpalle", "pincode": "501102", "category": "Mandal HQ"},
        {"town": "Pudur", "pincode": "501501", "category": "Mandal HQ"},
        {"town": "Yalal", "pincode": "501111", "category": "Mandal HQ"},
    ],
    "30. Jangaon District": [
        {"town": "Chilpur", "pincode": "506144", "category": "Mandal HQ & Temple Town"},
        {"town": "Lingala Ghanpur", "pincode": "506167", "category": "Mandal HQ"},
        {"town": "Narmetta", "pincode": "506224", "category": "Mandal HQ"},
        {"town": "Tarigoppula", "pincode": "506224", "category": "Mandal HQ"},
        {"town": "Zaffergadh", "pincode": "506143", "category": "Mandal HQ"},
    ],
    "31. Jayashankar Bhupalpally District": [
        {"town": "Chityal (Bhupalpally)", "pincode": "506504", "category": "Mandal HQ"},
        {"town": "Ghanpur (Bhupalpally)", "pincode": "506345", "category": "Mandal HQ & Historical Fort Town"},
        {"town": "Mahamutharam", "pincode": "506169", "category": "Mandal HQ"},
        {"town": "Malhar Rao", "pincode": "505504", "category": "Mandal HQ"},
        {"town": "Mogullapally", "pincode": "506169", "category": "Mandal HQ"},
        {"town": "Palimela", "pincode": "506504", "category": "Mandal HQ"},
        {"town": "Regonda", "pincode": "506348", "category": "Mandal HQ"},
        {"town": "Tekumatla", "pincode": "506348", "category": "Mandal HQ"},
    ],
    "32. Mulugu District": [
        {"town": "Govindaraopet", "pincode": "506344", "category": "Mandal HQ & Laknavaram Tourism Zone"},
        {"town": "Kannaigudem", "pincode": "506172", "category": "Mandal HQ"},
        {"town": "Wazeedu", "pincode": "507136", "category": "Mandal HQ & Godavari River Hub"},
    ],
    "33. Mahabubabad District": [
        {"town": "Nellikudur", "pincode": "506368", "category": "Mandal HQ"},
        {"town": "Narsimhulapet", "pincode": "506318", "category": "Mandal HQ"},
        {"town": "Gangaram", "pincode": "506134", "category": "Mandal HQ"},
        {"town": "Inugurthy", "pincode": "506112", "category": "Mandal HQ"},
        {"town": "Kothaguda", "pincode": "506135", "category": "Mandal HQ & Agency Forest Belt"},
        {"town": "Seerole", "pincode": "506381", "category": "Mandal HQ"},
        {"town": "Chinnagudur", "pincode": "506112", "category": "Mandal HQ"},
    ]
}

total_missing = sum(len(towns) for towns in TELANGANA_MISSING_TOWNS_BY_DISTRICT.values())
print(f"Total Uncovered Telangana Towns & Mandals Identified: {total_missing}")
